<a href="https://colab.research.google.com/github/Arjunb79/DS-ML-LAB/blob/main/ordinal_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder
data=asarray([['red'],['green'],['blue']])
print(data)
encoder=OrdinalEncoder()
result=encoder.fit_transform(data)
print(result)

[['red']
 ['green']
 ['blue']]
[[2.]
 [1.]
 [0.]]


In [ ]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
data=asarray([['red'],['green'],['blue']])
print(data)
encoder=OneHotEncoder(drop='first',sparse=False)
onehot=encoder.fit_transform(data)
print(onehot)



[['red']
 ['green']
 ['blue']]
[[0. 1.]
 [1. 0.]
 [0. 0.]]


In [ ]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
data=asarray([['red'],['green'],['blue']])
print(data)
encoder=OneHotEncoder(sparse=False)
onehot=encoder.fit_transform(data)
print(onehot)


[['red']
 ['green']
 ['blue']]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
